#include "efsm_core.h"
#include <stdio.h>
#include <stdint.h>
#include "debug.h"

uint16_t testBinary0Data[] =
{
	TEST_BIN_0_NUMBER_OF_STATES,
	TEST_BIN_0_TOTAL_NUMBER_OF_INPUTS,
	TEST_BIN_0_INITIAL_STATE,
	TEST_BIN_0_STATE_0_EFSM_BIN_INDEX,
	TEST_BIN_0_STATE_1_EFSM_BIN_INDEX,
	TEST_BIN_0_STATE_0_NUMBER_OF_INPUTS,
	TEST_BIN_0_STATE_0_NUMBER_OF_TRANSITIONS,
	TEST_BIN_0_STATE_0_EFSM_BIN_INDEX_OF_IQFN_DATA,	
	TEST_BIN_0_STATE_0_EFSM_BIN_INDEX_TRAN_0_DATA,
	TEST_BIN_0_STATE_0_IQFN_0_FRARR_INDEX,
	TEST_BIN_0_STATE_0_EFSM_BIN_INDEX_TRANSITION_ACTIONS_DATA,
	TEST_BIN_0_STATE_0_NEXT_STATE_AFTER_TRANSITION,
	TEST_BIN_0_STATE_0_NUMBER_OF_OPCODES,
	TEST_BIN_0_STATE_0_BOOLEAN_OPCODE_0_1,
	TEST_BIN_0_STATE_0_NUMBER_OF_TRANSITION_ACTIONS,
	TEST_BIN_0_STATE_0_ACTION_0_FRARR_INDEX,
	TEST_BIN_0_STATE_1_NUMBER_OF_INPUTS,
	TEST_BIN_0_STATE_1_NUMBER_OF_TRANSITIONS,
	TEST_BIN_0_STATE_1_EFSM_BIN_INDEX_OF_IQFN_DATA,
	TEST_BIN_0_STATE_1_EFSM_BIN_INDEX_TRAN_0_DATA,
	TEST_BIN_0_STATE_1_IQFN_0_FRARR_INDEX,
	TEST_BIN_0_STATE_1_EFSM_BIN_INDEX_TRANSITION_ACTIONS_DATA,
	TEST_BIN_0_STATE_1_NEXT_STATE_AFTER_TRANSITION,
	TEST_BIN_0_STATE_1_NUMBER_OF_OPCODES,
	TEST_BIN_0_STATE_1_OPCODE_0_1,
	TEST_BIN_0_STATE_1_NUMBER_OF_TRANSITION_ACTIONS,
	TEST_BIN_0_STATE_1_ACTION_0_FRARR_INDEX
};

EFSM_BINARY test0Binary;

/*Inputs*/
uint8_t inputA;

uint8_t IsA()
{
	return (inputA != 0);
}

uint8_t(*Test0Inputs[1])();

/*Actions (Outputs)*/
uint8_t light;

void TurnLightOn()
{
	light = 1;
	printf("Turning light on...");
}

void TurnLightOff()
{
	light = 0;
	printf("Turning light off...");
}

void (*Test0Actions[2])();

Test0Init()
{
	test0Binary.id = 4321;
	test0Binary.data = testBinary0Data;
	Test0Inputs[0] = &IsA;
	Test0Actions[0] = &TurnLightOn;
	Test0Actions[1] = &TurnLightOff;
}


