#ifndef EFSM_BINARY_PROTOCOL_H
#define EFSM_BINARY_PROTOCOL_H

#define EFSM_BIN_INDEX_NUMBER_OF_STATES												0
#define EFSM_BIN_INDEX_TOTAL_NUMBER_OF_INPUTS										1
#define EFSM_BIN_INDEX_INITIAL_STATE_IDENTIFIER										2


#define EFSM_BIN_INDEX_STATE_DATA_TABLE_OF_CONTENTS									3

/*Offsets relative to STATE HEADER data.*/
#define EFSM_STATE_HEADER_OFFSET_NUMBER_OF_INPUTS									0
#define EFSM_STATE_HEADER_OFFEST_NUMBER_OF_TRANSITIONS								1
#define EFSM_STATE_HEADER_OFFSET_BIN_INDEX_OF_IQFN_DATA								2
#define EFSM_STATE_HEADER_OFFSET_BIN_INDEX_OF_TRANSITION_DATA_BASE_INDICES			3

/*Offsets relative to TRANSITION INSTRUCTIONS data.*/
#define EFSM_TRN_INSTR_OFFSET_BIN_INDEX_FOR_TRN_ACTIONS_DATA						0
#define EFSM_TRN_INSTR_OFFSET_NEXT_STATE_AFTER_TRANSITION							1
#define EFSM_TRN_INSTR_OFFSET_NUMBER_OF_OPCODES										2
#define EFSM_TRN_INSTR_OFFSET_OPCODES												3 

/*Offsets relative to TRANSITION ACTIONS DATA.*/
#define EFSM_TRN_ACTIONS_DATA_OFFSET_NUMBER_OF_TRN_ACTIONS							0
#define EFSM_TRN_ACTIONS_DATA_OFFSET_TRN_ACTIONS_ARR_INDICES						1

#endif 
