#ifndef EFSM_BINARY_PROTOCOL_H
#define EFSM_BINARY_PROTOCOL_H

#define EFSM_BIN_INDEX_NUMBER_OF_STATES												0
#define EFSM_BIN_INDEX_TOTAL_NUMBER_OF_INPUTS										1
#define EFSM_BIN_INDEX_INITIAL_STATE_IDENTIFIER										2


#define EFSM_BIN_INDEX_STATE_DATA_TABLE_OF_CONTENTS									3

/*Offsets relative to STATE HEADER data.*/
#define EFSM_STATE_HEADER_OFFSET_NUMBER_OF_INPUTS									0
#define EFSM_STATE_HEADER_OFFEST_NUMBER_OF_TRANSITIONS								1
#define EFSM_STATE_HEADER_OFFSET_BIN_INDEX_OF_IQFN_DATA								2
#define EFSM_STATE_HEADER_OFFSET_FRARR_INDEX_FOR_GENERAL_ACTION						3
#define EFSM_STATE_HEADER_OFFSET_BIN_INDEX_OF_TRANSITION_DATA_BASE_INDICES			4

#endif 
