#ifndef EFSM_BINARY_PROTOCOL_H
#define EFSM_BINARY_PROTOCOL_H

#define EFSM_BIN_INDEX_NUMBER_OF_STATES												0
#define EFSM_BIN_INDEX_TOTAL_NUMBER_OF_INPUTS										1
#define EFSM_BIN_INDEX_INITIAL_STATE_IDENTIFIER										2


#define EFSM_BIN_INDEX_STATE_DATA_TABLE_OF_CONTENTS									3

#endif 
